import zlib
import json
import base64

teststr = dict(
    website="",
    sender_tel="UZFVQZWHCZ",
    primary_color="#419743",
    recipient_currency="JBCLVFLICP",
    recipient_tel="MCJSXQRWZO",
    terms_and_conditions="To Be Defined - Terms and Conditions",
    exchange_rate="TZKUYQIWND",
    recipient_address="YULLWYPHIQ",
    payout_fees="GWQTHPJYJH",
    card_id="crd_ThisIsaCoreBackendCardId",
    template_key="viamericas_remittance.email.body",
    sender_state="IZKUYHLSEC",
    team_id=304624,
    password="HAMDZLNMUN",
    alternate_logo_url=None,
    support_email="xavier@aptopayments.com",
    recipient_name="YYEPIJWOXM",
    sender_address="QOUSIXVTJV",
    sender_f_name="NXPITPHQDN",
    unsubscribe_url="http://local.ledge.me:2000/v1/user/notify/unsubscribe/X3FVT0DvR5TujCf%2Ffy0XOopM6sbv1IM8%2BZn7wkyBOfbN3r%2F7L8gDN%2BgVMtef%2BmHH",
    sender_country="BJGZYEPRCZ",
    sender_city="QEELZYCBUQ",
    sender_name="CWYVMVVAJB",
    company_address="To Be Defined - Company Address",
    language="en",
    transfer_amount="FBCRATDUUV",
    social_links="To Be Defined - Social Links",
    first_name="John SNow",
    total_paid="YQTPIQNGHV",
    funds_available="XQGGSWZENA",
    recipient_state="IXYDEZVGLR",
    transaction_date="UGMZSQEJMD",
    transfer_taxes="UTKRICVWBT",
    project_id=265012,
    payer_network="EHLWIENBTC",
    disclosure="QTFUJAJSUV",
    from_="1IDX4BGADV@aptopayments.com",
    folio_number="PLAGJVULTL",
    total_cost="UYCCHNUFWD",
    recipient_city="RWCNAYZHJC",
    transfer_fees="AHRMPWEPAH",
    sender_currency="VVOUPPLTUC",
    to="alberto@aptopayments.com",
    recipient_country="GOEAGBGRWP",
    logo_url=None,
    copyright_notice="To Be Defined - Copyright",
    w2ebsite="",
    s2ender_tel="UZFVQZWHCZ",
    p2rimary_color="#419743",
    r2ecipient_currency="JBCLVFLICP",
    r2ecipient_tel="MCJSXQRWZO",
    t2erms_and_conditions="To Be Defined - Terms and Conditions",
    e2xchange_rate="TZKUYQIWND",
    r2ecipient_address="YULLWYPHIQ",
    p2ayout_fees="GWQTHPJYJH",
    c2ard_id="crd_ThisIsaCoreBackendCardId",
    t2emplate_key="viamericas_remittance.email.body",
    s2ender_state="IZKUYHLSEC",
    t2eam_id=304624,
    p2assword="HAMDZLNMUN",
    a2lternate_logo_url=None,
    s2upport_email="xavier@aptopayments.com",
    r2ecipient_name="YYEPIJWOXM",
    s2ender_address="QOUSIXVTJV",
    s2ender_f_name="NXPITPHQDN",
    u2nsubscribe_url="http://local.ledge.me:2000/v1/user/notify/unsubscribe/X3FVT0DvR5TujCf%2Ffy0XOopM6sbv1IM8%2BZn7wkyBOfbN3r%2F7L8gDN%2BgVMtef%2BmHH",
    s2ender_country="BJGZYEPRCZ",
    s2ender_city="QEELZYCBUQ",
    s2ender_name="CWYVMVVAJB",
    c2ompany_address="To Be Defined - Company Address",
    l2anguage="en",
    t2ransfer_amount="FBCRATDUUV",
    s2ocial_links="To Be Defined - Social Links",
    f2irst_name="John SNow",
    t2otal_paid="YQTPIQNGHV",
    f2unds_available="XQGGSWZENA",
    r2ecipient_state="IXYDEZVGLR",
    t2ransaction_date="UGMZSQEJMD",
    t2ransfer_taxes="UTKRICVWBT",
    p2roject_id=265012,
    p2ayer_network="EHLWIENBTC",
    d2isclosure="QTFUJAJSUV",
    f2rom_="1IDX4BGADV@aptopayments.com",
    f2olio_number="PLAGJVULTL",
    t2otal_cost="UYCCHNUFWD",
    r2ecipient_city="RWCNAYZHJC",
    t2ransfer_fees="AHRMPWEPAH",
    s2ender_currency="VVOUPPLTUC",
    t2o="alberto@aptopayments.com",
    r2ecipient_country="GOEAGBGRWP",
    l2ogo_url=None,
    c2opyright_notice="To Be Defined - Copyright",
    w3ebsite="",
    s3ender_tel="UZFVQZWHCZ",
    p3rimary_color="#419743",
    r3ecipient_currency="JBCLVFLICP",
    r3ecipient_tel="MCJSXQRWZO",
    t3erms_and_conditions="To Be Defined - Terms and Conditions",
    e3xchange_rate="TZKUYQIWND",
    r3ecipient_address="YULLWYPHIQ",
    p3ayout_fees="GWQTHPJYJH",
    c3ard_id="crd_ThisIsaCoreBackendCardId",
    t3emplate_key="viamericas_remittance.email.body",
    s3ender_state="IZKUYHLSEC",
    t3eam_id=304624,
    p3assword="HAMDZLNMUN",
    a3lternate_logo_url=None,
    s3upport_email="xavier@aptopayments.com",
    r3ecipient_name="YYEPIJWOXM",
    s3ender_address="QOUSIXVTJV",
    s3ender_f_name="NXPITPHQDN",
    u3nsubscribe_url="http://local.ledge.me:2000/v1/user/notify/unsubscribe/X3FVT0DvR5TujCf%2Ffy0XOopM6sbv1IM8%2BZn7wkyBOfbN3r%2F7L8gDN%2BgVMtef%2BmHH",
    s3ender_country="BJGZYEPRCZ",
    s3ender_city="QEELZYCBUQ",
    s3ender_name="CWYVMVVAJB",
    c3ompany_address="To Be Defined - Company Address",
    l3anguage="en",
    t3ransfer_amount="FBCRATDUUV",
    s3ocial_links="To Be Defined - Social Links",
    f3irst_name="John SNow",
    t3otal_paid="YQTPIQNGHV",
    f3unds_available="XQGGSWZENA",
    r3ecipient_state="IXYDEZVGLR",
    t3ransaction_date="UGMZSQEJMD",
    t3ransfer_taxes="UTKRICVWBT",
    p3roject_id=265012,
    p3ayer_network="EHLWIENBTC",
    d3isclosure="QTFUJAJSUV",
    f3rom_="1IDX4BGADV@aptopayments.com",
    f3olio_number="PLAGJVULTL",
    t3otal_cost="UYCCHNUFWD",
    r3ecipient_city="RWCNAYZHJC",
    t3ransfer_fees="AHRMPWEPAH",
    s3ender_currency="VVOUPPLTUC",
    t3o="alberto@aptopayments.com",
    r3ecipient_country="GOEAGBGRWP",
    l3ogo_url=None,
    c3opyright_notice="To Be Defined - Copyright",
    w4ebsite="",
    s4ender_tel="UZFVQZWHCZ",
    p4rimary_color="#419743",
    r4ecipient_currency="JBCLVFLICP",
    r4ecipient_tel="MCJSXQRWZO",
    t4erms_and_conditions="To Be Defined - Terms and Conditions",
    e4xchange_rate="TZKUYQIWND",
    r4ecipient_address="YULLWYPHIQ",
    p4ayout_fees="GWQTHPJYJH",
    c4ard_id="crd_ThisIsaCoreBackendCardId",
    t4emplate_key="viamericas_remittance.email.body",
    s4ender_state="IZKUYHLSEC",
    t4eam_id=304624,
    p4assword="HAMDZLNMUN",
    a4lternate_logo_url=None,
    s4upport_email="xavier@aptopayments.com",
    r4ecipient_name="YYEPIJWOXM",
    s4ender_address="QOUSIXVTJV",
    s4ender_f_name="NXPITPHQDN",
    u4nsubscribe_url="http://local.ledge.me:2000/v1/user/notify/unsubscribe/X3FVT0DvR5TujCf%2Ffy0XOopM6sbv1IM8%2BZn7wkyBOfbN3r%2F7L8gDN%2BgVMtef%2BmHH",
    s4ender_country="BJGZYEPRCZ",
    s4ender_city="QEELZYCBUQ",
    s4ender_name="CWYVMVVAJB",
    c4ompany_address="To Be Defined - Company Address",
    l4anguage="en",
    t4ransfer_amount="FBCRATDUUV",
    s4ocial_links="To Be Defined - Social Links",
    f4irst_name="John SNow",
    t4otal_paid="YQTPIQNGHV",
    f4unds_available="XQGGSWZENA",
    r4ecipient_state="IXYDEZVGLR",
    t4ransaction_date="UGMZSQEJMD",
    t4ransfer_taxes="UTKRICVWBT",
    p4roject_id=265012,
    p4ayer_network="EHLWIENBTC",
    d4isclosure="QTFUJAJSUV",
    f4rom_="1IDX4BGADV@aptopayments.com",
    f4olio_number="PLAGJVULTL",
    t4otal_cost="UYCCHNUFWD",
    r4ecipient_city="RWCNAYZHJC",
    t4ransfer_fees="AHRMPWEPAH",
    s4ender_currency="VVOUPPLTUC",
    t4o="alberto@aptopayments.com",
    r4ecipient_country="GOEAGBGRWP",
    l4ogo_url=None,
    c4opyright_notice="To Be Defined - Copyright",
    w5ebsite="",
    s5ender_tel="UZFVQZWHCZ",
    p5rimary_color="#419743",
    r5ecipient_currency="JBCLVFLICP",
    r5ecipient_tel="MCJSXQRWZO",
    t5erms_and_conditions="To Be Defined - Terms and Conditions",
    e5xchange_rate="TZKUYQIWND",
    r5ecipient_address="YULLWYPHIQ",
    p5ayout_fees="GWQTHPJYJH",
    c5ard_id="crd_ThisIsaCoreBackendCardId",
    t5emplate_key="viamericas_remittance.email.body",
    s5ender_state="IZKUYHLSEC",
    t5eam_id=304624,
    p5assword="HAMDZLNMUN",
    a5lternate_logo_url=None,
    s5upport_email="xavier@aptopayments.com",
    r5ecipient_name="YYEPIJWOXM",
    s5ender_address="QOUSIXVTJV",
    s5ender_f_name="NXPITPHQDN",
    u5nsubscribe_url="http://local.ledge.me:2000/v1/user/notify/unsubscribe/X3FVT0DvR5TujCf%2Ffy0XOopM6sbv1IM8%2BZn7wkyBOfbN3r%2F7L8gDN%2BgVMtef%2BmHH",
    s5ender_country="BJGZYEPRCZ",
    s5ender_city="QEELZYCBUQ",
    s5ender_name="CWYVMVVAJB",
    c5ompany_address="To Be Defined - Company Address",
    l5anguage="en",
    t5ransfer_amount="FBCRATDUUV",
    s5ocial_links="To Be Defined - Social Links",
    f5irst_name="John SNow",
    t5otal_paid="YQTPIQNGHV",
    f5unds_available="XQGGSWZENA",
    r5ecipient_state="IXYDEZVGLR",
    t5ransaction_date="UGMZSQEJMD",
    t5ransfer_taxes="UTKRICVWBT",
    p5roject_id=265012,
    p5ayer_network="EHLWIENBTC",
    d5isclosure="QTFUJAJSUV",
    f5rom_="1IDX4BGADV@aptopayments.com",
    f5olio_number="PLAGJVULTL",
    t5otal_cost="UYCCHNUFWD",
    r5ecipient_city="RWCNAYZHJC",
    t5ransfer_fees="AHRMPWEPAH",
    s5ender_currency="VVOUPPLTUC",
    t5o="alberto@aptopayments.com",
    r5ecipient_country="GOEAGBGRWP",
    l5ogo_url=None,
    c5opyright_notice="To Be Defined - Copyright",
    w6ebsite="",
    s6ender_tel="UZFVQZWHCZ",
    p6rimary_color="#419743",
    r6ecipient_currency="JBCLVFLICP",
    r6ecipient_tel="MCJSXQRWZO",
    t6erms_and_conditions="To Be Defined - Terms and Conditions",
    e6xchange_rate="TZKUYQIWND",
    r6ecipient_address="YULLWYPHIQ",
    p6ayout_fees="GWQTHPJYJH",
    c6ard_id="crd_ThisIsaCoreBackendCardId",
    t6emplate_key="viamericas_remittance.email.body",
    s6ender_state="IZKUYHLSEC",
    t6eam_id=304624,
    p6assword="HAMDZLNMUN",
    user_id=398447
)


cmpstr = zlib.compress(json.dumps(teststr).encode('utf-8'))
temp = base64.b64encode(cmpstr).decode('ascii')
print('######################')
print(temp)
print(len(temp))
print(temp.__class__)
print('######################')
_temp_ = base64.b64decode(temp)
uncmpstr = json.loads(zlib.decompress(_temp_).decode('utf-8'))


print(len(json.dumps(teststr)))
# print(teststr)
# print(len(cmpstr))
# print(cmpstr)
print(len(json.dumps(uncmpstr)))
# print(uncmpstr)

assert uncmpstr == teststr


# fmt = '{:>8}: (length {}) {!r}'
# print(fmt.format('teststr', len(teststr), teststr))
# print(fmt.format('cmpstr', len(cmpstr), cmpstr))
# print(fmt.format('uncmpstr', len(uncmpstr), uncmpstr))
